# Site settings
email:fenglei_1994@hotmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Lei's Space
description: Hello! Welcome to Lei's Space.
url: ""
twitter_username: LeifengLei
default_img: 

# Profile settings
name: 冯蕾(Lei Feng)
profile_img: 
profile: Lei Feng is a UW graduate student
social:
  github:
  mail:fenglei_1994@hotmail.com
  linkedin:lei-feng-21951871
  facebook:100005717016726
  instagram:leisomethinglei
  twitter:LeifengLei
  

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
